### ISSUE TITLE
User Story:  Responsive Answer Buttons

### ISSUE THREAD

**Issue by LukeI50** [els-390/CI-Hackathon1-QuizProject#10]
As a user I would like to know whether I got the answer correct straight away, by seeing a visual indication of the correct answer.

## Acceptance Criteria:

1. option buttons are responsive to selection
2. correct answer highlights green when an option is clicked.

## Tasks:

- [x] check if option selected is equal to the answer.
- [x] highlight the correct answer Green
- [x] highlight the incorrect answers in Red
