### ISSUE TITLE
User Story: Clear Format

### ISSUE THREAD

**Issue by LukeI50** [els-390/CI-Hackathon1-QuizProject#11]
As a user, I want to be able to clearly see the question and each of my possible options/answers.

## Acceptance Criteria:

1. Create a box that clearly displays the question.
2. Clearly display each possible answer.
3. Clearly display a button for each answer option.

## Tasks:

- [x] create box for questions.
- [x] create container for the answers
- [x] create three buttons A, B, C (corresponding to the answer options)
