### ISSUE TITLE
User Story: Score Counter

### ISSUE THREAD

**Issue by LukeI50** [els-390/CI-Hackathon1-QuizProject#16]
As a user, I would like to know how well I am doing on the quiz as I take it.

## Acceptance Criteria:

1. A score counter displayed on the screen
2. shows correct questions of total
3. increases by 1 per correct answer

## Tasks:

- [x] create an element for the score counter (can just be a p element, but will likely need a div parent to make it look alright).
- [x] add JavaScript to increase the count by 1 per correct answer clicked.
- [x] make the innerContent of the p element update
