### ISSUE TITLE
User Story: Data Structure

### ISSUE THREAD

**Issue by LukeI50** [els-390/CI-Hackathon1-QuizProject#17]
As a product owner, I want to have lots of questions for the users to answer.

## Acceptance Criteria:

1. Implement a 2 dimensional array
2. x, y; coordinate x will contain each topic group 
3. coordinate y = 0 contain topic name as string
4. all y coordinates > 0 will contain question, answers objects.

## Tasks:

- [x] create a const variable with an array. (array x)
- [x] add second dimension to array (each item in the main array is another array). (sub arrays are y)
- [x] add all topics to each iteration of y = 0. i.e., 0, 0, = topic name, 1, 0, = topic2 name, etc.
- [x] add question objects relevant to topic of y values > 0
