### ISSUE TITLE
User Story: Start Button

### ISSUE THREAD

**Issue by LukeI50** [els-390/CI-Hackathon1-QuizProject#22]
As a user, I would like to have a start button.

## Acceptance Criteria:

1. A start button on the screen
2. first question appears once the start has been clicked.

## Tasks:

- [x] Create start button
- [x] hide questions until start button is clicked
- [x] hide start button once start button is clicked
