### ISSUE TITLE
User Story: Add Favicon to Web Page

### ISSUE THREAD

**Issue by LukeI50** [els-390/CI-Hackathon1-QuizProject#23]
As a user, I want to be able to distinguish the quiz tab from others easily, using a favicon to identify it quickly.

## Acceptance Criteria:

1. cornish flag visible as favicon on browser tab

## Tasks:

- [x] add link element to html
- [x] add favicon to assets/images
- [x] links href to be directed to favicon in images
