### ISSUE TITLE
USER STORY: User can enter their name.

### ISSUE THREAD

**Issue by katepz** [els-390/CI-Hackathon1-QuizProject#25]
As a user I want to enter my name So that I can save my scores.

## Acceptance Criteria:

1. An input field enables the user to input their name.
2. The user's score will be saved with their name so that progress can be measured.
3. On revisting the site the user can access previos scores.

## Tasks:

- [ ] Task 1 Create an input field for the user to enter their name.
- [ ] Task 2 Store the user's input  and score.
- [ ] Task 3 Access the data on the next visit.
