### ISSUE TITLE
USER STORY: Share Score Option

### ISSUE THREAD

**Issue by els-390** [els-390/CI-Hackathon1-QuizProject#26]
As a user I want to be able to easily access a share button to share my scores to social media. 

## Acceptance Criteria:

1. Visible share button
2. Multiple platform options to share scores on

## Tasks:

- [ ] Create buttons for different platform options 
- [ ] Add URLs for relevant website to link to
- [ ] Test buttons work as expected
- [ ] Style buttons to match theme
